### ISSUE TITLE
Self-closing tags being changed

### ISSUE THREAD

**Issue by rickysullivan** [zurb/inky#14]
```
<hr />
```

Becomes

```
<hr>
```

**Comment by rickysullivan** [comment]
I think this is why: https://github.com/cheeriojs/cheerio/issues/598

**Comment by gakimball** [comment]
Fixed via 9bbed0858f7841cdd78b4b2a14b73a2c1e5ec73c

**Comment by gakimball** [comment]
Spoke too soon—there's one potential issue I'll need to review tomorrow.

Cheerio's XML mode does preserve self-closing tags, but it also converts empty tags into self-closing tags. For example, the expander in the column markup:

```html
<th class="expander"></th>
```

Becomes:

```html
<th class="expander" />
```

If this breaks some random email client we'll need to figure that out.

**Comment by gakimball** [comment]
Reviewed this with the team this morning, and we're going to keep `xmlMode` off for now. It's been working for us so far, and we're two days from the launch so we don't want to risk breaking anything.

If any framework bugs arise from not strictly adhering to XHTML, we can address them on a case-by-case basis.

**Comment by rickysullivan** [comment]
Bugger. Would be good to add this xmlMode option in for testing purposes.

I was looking into Cheerio to see if there was an option to ignore empty tags. I'm about to start some testing in Litmus to see if there are any issues. It's valid XHTML, and there are other self closing tags we use that don't break.

**Comment by gakimball** [comment]
It may be valid XHTML, but Outlook doesn't parse HTML as valid anything ;)

I believe the grid is the only component that prints an empty tag, which is the expander. So if `<th class="expander" />` doesn't break in any email client, then we can introduce the change in a future version of the framework.

**Comment by rickysullivan** [comment]
Could always insert a ``&nbsp;`` :)
