### ISSUE TITLE
expander class breaks full-width image

### ISSUE THREAD

**Issue by leffi7** [zurb/inky#16]
Hi,

Inky automatically generates an expander class. This causes some problems when I try to show an image in a table cell.

`
<row>
<columns small="5" large="5">
      <p>some text</p>
    </columns>
    <columns small="5" large="5">
      <img src="http://link-to-image.png" width="218" height="40" >
    </columns>
</row>
<row>
    <columns small="10" large="10">
      <img src="http://link-to-image.jpg" >
    </columns>
</row>
`

Both images cover only half width of the table cell instead of the full width. This happens in multiple clients.

After running the inline css, I manually deleted every expander cell. When I checked in Litmus, all the clients showed the correct result.

I am not sure why this expander cell is added? Is there a way to prevent inky from creating the expander class? Or is there a workaround?

thx!

**Comment by leffi7** [comment]
I added gulp-html-remove, which removes all cells with class="expander".
https://www.npmjs.com/package/gulp-html-remove

Works well on every client now...

Still curious about the expander though :)

**Comment by gakimball** [comment]
@tdhartwick or @rafibomb can you chime in?

**Comment by rafibomb** [comment]
Is there a specific client you had this issue with? The expander is specifically for some version of Outlook. We have seen the expander shrink some images on Outlook 2000, 2002, 2003.

**Comment by leffi7** [comment]
Correct. And these are still the most popular Outlook clients according to our analytics.
But like I said, by removing the expander it works fine on every client.

**Comment by gakimball** [comment]
@rafibomb Let's add a visual test to the foundation-emails repo that recreates this.

**Comment by rafibomb** [comment]
This is the same as https://github.com/zurb/foundation-emails/issues/246

With Inky, removing the expander on columns < 12 containing an image. 

I added the visual test here: 8ed535c

**Comment by rafibomb** [comment]
The expander is needed for full -width columns that have content that doesn't fill the full width. It ensures the column goes full width in some versions of Outlook.

**Comment by rafibomb** [comment]
We resolved this in 2.0. Let us know if you still see the issue by opening a new issue. Thanks!
