### ISSUE TITLE
Callout innermost cell should be a TH

### ISSUE THREAD

**Issue by BenoitZugmeyer** [zurb/inky#19]
According to [the SCSS](https://github.com/zurb/foundation-emails/blob/1519cfc03aa4649cd52e5223deb04ebd2682ded7/scss/components/_callout.scss#L50), the callout cell should be a `TH`, but inky outputs a `TD` (as per [the tests](https://github.com/zurb/inky/blob/27cf548474c5b891145a074543096573d4f16208/test/components.js#L209)). Thus, [coloring classes](http://foundation.zurb.com/emails/docs/callout.html#coloring-classes) are not coloring anything.

**Comment by andrewmnlv** [comment]
#20

**Comment by gakimball** [comment]
Merged #20 and published Inky 1.3.4. Thanks @andrewmnlv!
