### ISSUE TITLE
Why not Grunt?

### ISSUE THREAD

**Issue by XmlmXmlmX** [zurb/inky#22]
Is there a reason why grunt isn't supported?

**Comment by gakimball** [comment]
We use Gulp for all of our templates, so supporting other build systems right away wasn't in the cards for us.

However, the plugin supports [programmatic use](https://github.com/zurb/inky#programmatic-use), so making a Grunt plugin would be fairly easy.

If you're interested in publishing one, we can link to it on the readme here.

**Comment by Miw0** [comment]
@XmlmXmlmX see #44 :)

**Comment by XmlmXmlmX** [comment]
@Miw0 thx
