### ISSUE TITLE
Bad encoding for an apostrophe

### ISSUE THREAD

**Issue by vincentducorps** [zurb/inky#24]
**How can we reproduce this bug?**

If you write an apostrophe :
`<p>Merci de m'appeler</p>`

**What did you expect to happen?**

` <p>Merci de m&#39;appeler</p>`

**What happened instead?**

` <p>Merci de m&apos;appeler</p>`

Probably due to cheerio

**What email clients does this happen in?**
All
Visible in Outlook 

> `Merci de m&apos;appeler`

**Comment by rafibomb** [comment]
It's most likely due to the inliner. We recently updated the code that is handling it. We'll move this over to the main repo https://github.com/zurb/foundation-emails/issues/281
