### ISSUE TITLE
handle mustache curly braces

### ISSUE THREAD

**Issue by luposky** [zurb/inky#28]
I use foundation-emails / inky to generate email templates. These templates have {{tags}} inside and are filled with mustache data before sending it.

In inky template I have this line:
`<button href="{{buttonUrl}}">{{buttonText}}</button>`

but compiling with inky completely drop my {{tags}}:
`<table class="button text-center"><tr><td><table><tr><td></td></tr></table></td></tr></table>`

desidered result:
`<table class="button text-center"><tr><td><table><tr><td><a href="{{buttonUrl}}">{{buttonText}}</a></td></tr></table></td></tr></table>`

Best regards,
Luca

**Comment by ignasbernotas** [comment]
I've got a similar problem. Laravel's Blade syntax uses curly braces, so when trying to use:
`{{ "{{ trans('emails.account.invitation.text') }}" }}` I get an empty string.

**Comment by ignasbernotas** [comment]
So I've figured out that panini uses handlebars. So far I got to:
`\{{ route('settings.account.invite.confirm', [$token, $id]) }}` 
which produces:
`{{ route(&apos;settings.account.invite.confirm&apos;, [$token, $id]) }}`

haven't found a way to disable html entity encoding.

**Comment by bumbu** [comment]
you can use `{{{{raw}}}}  put whatever you want here @#$%^&*()+)(*&^%<>'  {{{{/raw}}}}

**Comment by McJay** [comment]
I have similar case where I would need to use curly braces and disable html entity encoding case by case or globally if not possible to just escape the enities. Anyone have way to handle this situation?

**Comment by rafibomb** [comment]
There is PR that is a work in progress to stop the character encoding https://github.com/zurb/inky/pull/37

This should solve you use case. It would be awesome to add this test case to this page https://github.com/zurb/foundation-emails/blob/develop/test/visual/pages/inliner-bugs.html so when it's fixed there can be some regression testing - thanks!

**Comment by rafibomb** [comment]
Maybe some kind of `<raw>` tag to wrap content that should be ignored. Perhaps `<ignore>`?

**Comment by rafibomb** [comment]
This looks like a great one to get into 2.2.

We're thinking a `<raw>` tag might be good because a lot of JS and handlebars syntaxes use this. Is anyone able to take a stab at this one?

**Comment by rafibomb** [comment]
This is in 2.2.1!

**Comment by diomededavid** [comment]
Raw does not work when wrapping less than and greater than like so: <raw><<Text here>></raw>. Would decode work?

**Comment by anthonybrebion** [comment]
Hi,

I'm trying to use the raw tag to not process a template variable used by our ESP but it doesn't seem to work as expected.

Ex: <raw>{{unsubscribe_link}}</raw> doesn't output anything
and if I use a one of the Custom data set at the top of my page, it outputs it. (ex: <raw>{{subject}}</raw>)

**Comment by twistedpixel** [comment]
As pointed out by @diomededavid <raw> does not work with greater-than and less-than so php tags still get mangled. Is there a way round this? Is it a known issue? In my opinion, it should ignore absolutely everything between the tags without exception so I'm not sure if this is intended behavior.

**Comment by diomededavid** [comment]
@twistedpixel  One way you could work around it is to replace your <, and > with &lt; and gt; tags. You can add a find/replace gulpscript/function after the inliner fuction in your gulp script to find replace  for &lt; and gt; tags and probably colons, you will have to encode some tags in your html to bypass the inliner.

**Comment by twistedpixel** [comment]
Yep, that's what I'm currently doing but it just feels dirty. It ruins object attributes too ($var->att) and will likely affect other things I haven't come across yet so it's not particularly reliable.

I'm curious: is it intended or a bug? If intended, I might just have it run through Smarty or Blade, avoiding PHP tags with the inliner altogether. Feels cleaner, if not overkill.
