### ISSUE TITLE
Cyrillic characters disallow encode

### ISSUE THREAD

**Issue by Olegatro** [zurb/inky#32]
How  disallow encode Cyrillic characters ?

Example

`<a href="#" class="header-menu__item">&#x41C;&#x443;&#x436;&#x447;&#x438;&#x43D;&#x430;&#x43C;</a>`

Must be 

`<a href="#" class="header-menu__item">Мужчинам</a>`

**Comment by goodinmech** [comment]
```
function parse() {
  gulp.src('src/pages/**/*.html')
    .pipe(inky({cheerio: {decodeEntities: false}}))
    .pipe(gulp.dest('dist'));
}
```

**Comment by Olegatro** [comment]
Yes, I see, but without pr https://github.com/zurb/inky/pull/31 it doesn't work.
Anyway, I think the issue can close.
