### ISSUE TITLE
Standalone / Browser build

### ISSUE THREAD

**Issue by bolandrm** [zurb/inky#33]
Would it be possible to have a standalone build of inky, similar to https://github.com/Daniel15/babel-standalone ?  

I'd like to create a rails plugin to use inky within the asset pipeline.

I might be able to implement this myself if someone could outline where to start and/or generally how to accomplish it.

**Comment by kball** [comment]
We'd definitely be open to a standalone build; I can take a look at pulling together some resources on how to get it to happen.

That said, an implementation of inky in ruby (inky-rb) is in progress, with the intent that you could use it directly in the rails pipeline without any need to pull in a javascript runtime.  That should be available in the order of the next month... would you be interested in being part of the early testing?  And knowing this, are you still interested in developing a standalone build?

**Comment by bolandrm** [comment]
@kball thanks for the reply!  Yes, I'd like to be part of the early testing of the Ruby version, and given that I would not need the standalone JS build.

**Comment by rafibomb** [comment]
@kball Is the Ruby version in a place where it can be published for testing or contributions?

**Comment by kball** [comment]
I will get it there on Friday

**Comment by alethea** [comment]
@kball I would also be interested in helping test and contribute to the ruby version.

**Comment by mfontani** [comment]
Just FYI, I've got a Perl port at https://github.com/mfontani/p5-Inky

**Comment by shreve** [comment]
@kball I'm also interested in using/testing/contributing to inky-rb.

**Comment by rafibomb** [comment]
@shreve Awesome! We're getting close to releasing the RB version. We're looking to get a first version out before the 2.2 release which is early June. We'll need people to help test and suggest updates when it's out. We'll post back here!

**Comment by rafibomb** [comment]
Just following up here:
Invites to the Ruby version of Inky have been sent!

It's the Inky-rb repo. You'll find the Ruby Gem of Foundation for Emails here: https://github.com/zurb/foundation-emails/tree/ruby-gem-setup

We'd love any feedback you have on the setup or usage!

**Comment by rafibomb** [comment]
@mfontani Awesome! We're adding your resource to our site http://foundation.zurb.com/emails/resources.html which gets 30k visitors a day! Well done!

**Comment by westonganger** [comment]
@rafibomb the link you posted to the ruby gem setup does not work

**Comment by michaelmcandrew** [comment]
I know this issue is mostly about ruby, but since this issue mentions a browser build, I wanted to point the googlers over here: https://github.com/zurb/inky/issues/67
