### ISSUE TITLE
babel-register module does not come out of the box

### ISSUE THREAD

**Issue by Lucaz5520** [zurb/inky#38]
Not a big deal but I just wanted to bring this to your attention that when I downloaded and used inky "npm run" did not work because it said **babel-register module required** so then I just installed it via NPM and it worked fine. Would be a good idea to have that already included.

**Comment by rafibomb** [comment]
The error message is annoying though we haven't seen it cause real world issues.

We're using `npm start` to run the project. There is an open issue for this on the Sites repo, that uses the same build system. We'll close this here - thanks!
