### ISSUE TITLE
text-center on button doesn't center the text

### ISSUE THREAD

**Issue by AndreasGalster** [zurb/inky#39]
When using text-center on a <button> I'd expect it to center the text on the button. Text doesn't center in a button when the text wraps into two lines (on a smaller device for example).

**Comment by rafibomb** [comment]
The way to center a button reliably (Outlook 2007,10,13) requires align="center" to be added. So instead you'll wrap it in a `<center>` tag as detailed here: http://foundation.zurb.com/emails/docs/alignment.html#centering-a-button

**Comment by elcaptain** [comment]
<center> centers the button correctly but the the text inside the button is still left aligned. see: https://github.com/foundation/foundation-emails/issues/819

**Comment by elcaptain** [comment]
A possible fix is to add `table.button.text-center > tbody > tr > td > table > tbody > tr > td > a {
    text-align: center;
}` to your css to inline the desired css
