### ISSUE TITLE
column offset not working on colums that have collapse class set on row

### ISSUE THREAD

**Issue by AndreasGalster** [zurb/inky#40]
I'd expect columns to still have an offset when setting row class='collapse'. Right now that's not happening though. Is this an intended behavior? I consider it a bug.

**Comment by rafibomb** [comment]
Might be related to this: https://github.com/zurb/foundation-emails/issues/358

If so, you can add to the conversation there on the main repo since it's a CSS issue rather than Inky.

We'll close this here - thanks!
