### ISSUE TITLE
Is it possible to configure the speation between links in  a menu?

### ISSUE THREAD

**Issue by ricardopolo** [zurb/inky#43]
We want something like this

<img width="135" alt="screen shot 2016-05-11 at 6 27 00 pm 1" src="https://cloud.githubusercontent.com/assets/1263856/15199687/0ac919d6-17a6-11e6-961f-595aed368384.png">

But using the menu in inky we get
<img width="318" alt="screen shot 2016-05-11 at 6 26 35 pm" src="https://cloud.githubusercontent.com/assets/1263856/15199669/ed846aa6-17a5-11e6-8eb9-560326852a4d.png">

So, is it possible to adjust that spacing? :)

Thanks

**Comment by rafibomb** [comment]
There is padding on the menu component: `.menu-item`

There is a settings variable for this as well: `$menu-item-padding: 10px;`

If you have more questions, the [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by ricardopolo** [comment]
And why is this configured in variables and not in the code of pages?
I mean if we need mutliple menus with difference paddings in each one this wont work.
