### ISSUE TITLE
Mention grunt-inky Grunt plugin in your README?

### ISSUE THREAD

**Issue by Miw0** [zurb/inky#44]
Hello there! :)

Firstly, I want to thank you for your awesome work with this template language! It saved me alot of time and brain!

After that I want to introduce you a Grunt plugin I published recently to be able to easily use Inky via Grunt.js and wanted to ask you, if you want to mention it in your README.md so Grunt users see it easily.

The Grunt plugin can be found here: https://www.npmjs.com/package/grunt-inky

I don't want to advertise my own plugin, I am just asking because I saw a "gulp way" of using Inky and saw the need for a "Grunt way" for those Grunt users out there. I can fully understand if you don't want to mention it on your README. I will be fine with that.

Greetings,
Miw0

**Comment by rafibomb** [comment]
Hey Miw0! Thanks for the Kudos! 

This is a great resource you put out there! Love the ascii art! We'll add it to our Wiki here on GitHub as well as the resources page on Foundation: http://foundation.zurb.com/emails/resources.html 

It get's a ton of traffic daily and we're happy to promote your version!

**Comment by Miw0** [comment]
I'm really happy to hear this! Thanks alot! :+1:
