### ISSUE TITLE
Allow attributes on columns

### ISSUE THREAD

**Issue by bolatovumar** [zurb/inky#47]
It would be nice to be able to specify an attribute such as "valign" on a <columns> element. Some e-mail clients do not respect "vertical-align: top" rule in CSS (Outlook 2007, 2010, 2013) and as a result content of a column can end up floating in the middle of the column if another column contains more content.

Would this be something you would like someone to take a stab at?

**Comment by rafibomb** [comment]
That's right! There is an open PR for it that we're looking to add for 2.2 https://github.com/zurb/inky/pull/45
