### ISSUE TITLE
Tables and align attribute

### ISSUE THREAD

**Issue by Xochi** [zurb/inky#51]
I've found adding the html attribute align="center" to tables essential for rendering center aligned elements in outlook 2013 and 2016 in certain circumstances. I am currently adding the attribute manually after rendering my completed code to the dist folder. Would others see a benefit in having an option for defining this attribute within the precompiled templates? or does this exist? Other useful attributes for tables include cellpadding="0" and cellspacing="0" although I haven't seen a need for these so far as outlook rendering.

**Comment by rafibomb** [comment]
There is a pending PR to pass in the attributes https://github.com/zurb/inky/pull/45

This should help get those alignments set!

**Comment by rafibomb** [comment]
I also have not seen the need for cell spacing and cell padding but definitely cool to use valign in our designs.
