### ISSUE TITLE
Let buttons open in new tab

### ISSUE THREAD

**Issue by danbrellis** [zurb/inky#52]
Looking through the source code, I see how buttons are converted to anchor tags in componentFactory.js. Yet, there is no way to set target="_blank". I think this could be an easy addition and for my purposes, useful. Basically, if I wanted to take my email and host it on my website as a sort of archive, it would be beneficial to have certain links open in a new tab.

Something simple, like this starting at line 29 under ```case this.components.button```: 

```
var target = '';
			
if (element.attr('target')) {
    target = ' target="' + element.attr('target') + '"';
}
			
// If we have the href attribute we can create an anchor for the inner of the button;
if (element.attr('href')) {
    inner = format('<a href="%s"%s>%s</a>', element.attr('href'), target, inner);
}
```

**Comment by rafibomb** [comment]
Looks there was a PR merged for this already https://github.com/zurb/inky/pull/42
It will go out with 2.2 this month!
