### ISSUE TITLE
Spacer table is causing text to display funny

### ISSUE THREAD

**Issue by rickysullivan** [zurb/inky#68]
The spacer class needs `float: none` on it to prevent weird things from happening to items of text below spacer tables. See how the words `Hi Wolfman` appear to be joining?

Before:
![image](https://cloud.githubusercontent.com/assets/437480/20172414/123d4e1c-a789-11e6-8501-abae8ebcd24e.png)

After: 
![image](https://cloud.githubusercontent.com/assets/437480/20172495/6935553e-a789-11e6-9027-743209dcc79a.png)

**Comment by rafibomb** [comment]
Weird! I hadn't seen it before. Can you share a test case to reproduce it? Adding CSS `float: none` helped?

**Comment by rickysullivan** [comment]
My apologies, I should have tested this before submitting.

I'm using [Juice](https://github.com/Automattic/juice) to inline my emails (not using the Zurb stack, yet). Turns out it's a setting issue: `applyAttributesTableElements`was adding the `float: left`.
