### ISSUE TITLE
Implementation of gitflow workflow

### ISSUE THREAD

**Issue by navelpluisje** [zurb/inky#7]
Speaks for itself I think

**Comment by gakimball** [comment]
We don't use gitflow for any of our projects and don't currently have plans to.

**Comment by navelpluisje** [comment]
Ok. Just an idea. We use it as our workflow and work pretty good.

**Comment by gakimball** [comment]
To be sure, we haven't always had the responsible Git processes on the Foundation team, but we're working on it. :)
