### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by mortenson** [zurb/inky#75]
This repository is missing a license - I assume it's MIT like zurb/foundation-emails, but without a LICENSE file I can't confirm that for use in my projects. Could one be added?

**Comment by gakimball** [comment]
I added a `LICENSE` file to the v2 I'm working on: 14790024c31076a346ee558102ce202ecd359597

As for the current version, the `package.json` indicates that the license is MIT: <https://github.com/zurb/inky/blob/6b7810059b6b00b0d831a2f1f0c9d8ec32349c77/package.json#L35>
